#DDL COMMANDS
use mysql; 
CREATE TABLE STUDENT( 
student_id INT,
name VARCHAR(20),
major VARCHAR(20),
PRIMARY KEY(student_id)
);

DESCRIBE STUDENT;

ALTER TABLE STUDENT ADD cgpa DECIMAL(3,2);
ALTER TABLE STUDENT DROP COLUMN cgpa;
TRUNCATE STUDENT;
DROP TABLE STUDENT;